import type { MigrateDownArgs, MigrateUpArgs } from '@payloadcms/db-postgres'
import { sql } from '@payloadcms/db-postgres'

/**
 * Migration: reconcile the production schema with the Payload config.
 *
 * A 2026-09-17 audit compared every table, column, index and foreign key Payload
 * expects against the live database. Earlier hand-written migrations had left drift:
 *
 *   A. `payload_locked_documents_rels.blog_leads_id` (+ FK, index) was never created
 *      when the blog-leads collection was added (20260618). Payload's document-lock
 *      query selects it, so GET /admin returned 500 and every update() failed — the
 *      same bug 20260619_010000 fixed for ev_report_leads.
 *   B. 20260526 converted `pages_blocks_faq_items.answer` from Lexical JSONB to text,
 *      but not the versions table, so saving a page with an FAQ block failed with
 *      `invalid input syntax for type json`.
 *   C. `executive_summary_preview` is richText (jsonb) in the config but varchar in the
 *      DB. Values are already Lexical JSON text; two old plain-text drafts get wrapped
 *      in a Lexical paragraph.
 *   D. 25 indexes + 20 FKs whose Drizzle names exceed Postgres' 63-character identifier
 *      limit were never created. Postgres truncates the names here — that is expected.
 *
 * Benign leftovers are intentionally left alone: text-vs-varchar columns, nullable
 * columns from removed fields (meta_image_id, expert_id, companies_id) and the
 * redirects tables.
 *
 * The .json snapshot beside this file was generated by `payload migrate:create` and is
 * the baseline of the full schema: from here on `pnpm payload migrate:create <name>`
 * produces correct diffs, so migrations no longer need to be written by hand.
 *
 * Every step checks current state first, so it is safe to re-run.
 */

export async function up({ db }: MigrateUpArgs): Promise<void> {
  // A. Document-locking relation for blog-leads
  await db.execute(sql`
    ALTER TABLE "payload_locked_documents_rels" ADD COLUMN IF NOT EXISTS "blog_leads_id" integer;
    CREATE INDEX IF NOT EXISTS "payload_locked_documents_rels_blog_leads_id_idx"
      ON "payload_locked_documents_rels" USING btree ("blog_leads_id");
    DO $$ BEGIN
      ALTER TABLE "payload_locked_documents_rels"
        ADD CONSTRAINT "payload_locked_documents_rels_blog_leads_fk"
        FOREIGN KEY ("blog_leads_id") REFERENCES "public"."blog_leads"("id")
        ON DELETE cascade ON UPDATE no action;
    EXCEPTION WHEN duplicate_object THEN null; END $$;
  `)

  // B. FAQ answers in page versions: Lexical JSONB -> plain text (same extraction as 20260526)
  await db.execute(sql`
    DO $$
    BEGIN
      IF (SELECT data_type FROM information_schema.columns
          WHERE table_schema = 'public' AND table_name = '_pages_v_blocks_faq_items'
            AND column_name = 'answer') = 'jsonb' THEN
        ALTER TABLE "_pages_v_blocks_faq_items" ADD COLUMN "answer_text" varchar;

        UPDATE "_pages_v_blocks_faq_items"
        SET "answer_text" = (
          SELECT string_agg(paragraph_text, E'\n\n' ORDER BY para_ord)
          FROM (
            SELECT para_ord, string_agg(leaf->>'text', '' ORDER BY leaf_ord) AS paragraph_text
            FROM (
              SELECT para_row.ordinality AS para_ord, leaf_row.ordinality AS leaf_ord, leaf_row.value AS leaf
              FROM
                jsonb_array_elements(COALESCE("answer"->'root'->'children', '[]'::jsonb))
                  WITH ORDINALITY AS para_row(para, ordinality),
                jsonb_array_elements(COALESCE(para_row.para->'children', '[]'::jsonb))
                  WITH ORDINALITY AS leaf_row(value, ordinality)
              WHERE leaf_row.value->>'text' IS NOT NULL AND leaf_row.value->>'text' != ''
            ) leaves
            GROUP BY para_ord
            HAVING string_agg(leaf->>'text', '') != ''
          ) paragraphs
        )
        WHERE "answer" IS NOT NULL AND jsonb_typeof("answer") = 'object';

        UPDATE "_pages_v_blocks_faq_items"
        SET "answer_text" = "answer" #>> '{}'
        WHERE "answer" IS NOT NULL AND jsonb_typeof("answer") = 'string' AND "answer_text" IS NULL;

        ALTER TABLE "_pages_v_blocks_faq_items" DROP COLUMN "answer";
        ALTER TABLE "_pages_v_blocks_faq_items" RENAME COLUMN "answer_text" TO "answer";
      END IF;
    END $$;
  `)

  // C. Earnings executive summary preview: varchar -> jsonb (main + versions)
  await db.execute(sql`
    DO $$
    DECLARE t record;
    BEGIN
      FOR t IN SELECT * FROM (VALUES
        ('earnings_analyses', 'executive_summary_preview'),
        ('_earnings_analyses_v', 'version_executive_summary_preview')
      ) AS v(tbl, col) LOOP
        IF (SELECT data_type FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = t.tbl AND column_name = t.col) <> 'jsonb' THEN
          EXECUTE format($f$
            ALTER TABLE %1$I ALTER COLUMN %2$I TYPE jsonb USING (
              CASE
                WHEN %2$I IS NULL OR btrim(%2$I) = '' THEN NULL
                WHEN pg_input_is_valid(%2$I, 'jsonb') THEN %2$I::jsonb
                ELSE jsonb_build_object('root', jsonb_build_object(
                  'type', 'root', 'format', '', 'indent', 0, 'version', 1, 'direction', 'ltr',
                  'children', jsonb_build_array(jsonb_build_object(
                    'type', 'paragraph', 'format', '', 'indent', 0, 'version', 1,
                    'direction', 'ltr', 'textFormat', 0,
                    'children', jsonb_build_array(jsonb_build_object(
                      'type', 'text', 'text', %2$I, 'format', 0, 'style', '', 'mode', 'normal',
                      'detail', 0, 'version', 1))))))
              END)
          $f$, t.tbl, t.col);
        END IF;
      END LOOP;
    END $$;
  `)

  // D. Indexes + foreign keys never created because their names exceed 63 characters
  await db.execute(sql`
    CREATE INDEX IF NOT EXISTS "pages_blocks_free_transcript_hero_compliance_items_parent_id_idx" ON "pages_blocks_free_transcript_hero_compliance_items" USING btree ("_parent_id");
    CREATE INDEX IF NOT EXISTS "pages_blocks_pricing_comparison_left_panel_features_parent_id_idx" ON "pages_blocks_pricing_comparison_left_panel_features" USING btree ("_parent_id");
    CREATE INDEX IF NOT EXISTS "pages_blocks_pricing_comparison_right_panel_features_parent_id_idx" ON "pages_blocks_pricing_comparison_right_panel_features" USING btree ("_parent_id");
    CREATE INDEX IF NOT EXISTS "pages_blocks_research_applications_applications_insights_order_idx" ON "pages_blocks_research_applications_applications_insights" USING btree ("_order");
    CREATE INDEX IF NOT EXISTS "pages_blocks_research_applications_applications_insights_parent_id_idx" ON "pages_blocks_research_applications_applications_insights" USING btree ("_parent_id");
    CREATE INDEX IF NOT EXISTS "pages_blocks_mockup_builder_transcript_content_sections_order_idx" ON "pages_blocks_mockup_builder_transcript_content_sections" USING btree ("_order");
    CREATE INDEX IF NOT EXISTS "pages_blocks_mockup_builder_transcript_content_sections_parent_id_idx" ON "pages_blocks_mockup_builder_transcript_content_sections" USING btree ("_parent_id");
    CREATE INDEX IF NOT EXISTS "pages_blocks_mockup_builder_dashboard_content_tiles_parent_id_idx" ON "pages_blocks_mockup_builder_dashboard_content_tiles" USING btree ("_parent_id");
    CREATE INDEX IF NOT EXISTS "pages_blocks_mockup_builder_chart_content_data_points_parent_id_idx" ON "pages_blocks_mockup_builder_chart_content_data_points" USING btree ("_parent_id");
    CREATE INDEX IF NOT EXISTS "_pages_v_blocks_free_transcript_hero_compliance_items_parent_id_idx" ON "_pages_v_blocks_free_transcript_hero_compliance_items" USING btree ("_parent_id");
    CREATE INDEX IF NOT EXISTS "_pages_v_blocks_custom_transcript_hero_process_steps_parent_id_idx" ON "_pages_v_blocks_custom_transcript_hero_process_steps" USING btree ("_parent_id");
    CREATE INDEX IF NOT EXISTS "_pages_v_blocks_custom_transcript_hero_trust_stats_parent_id_idx" ON "_pages_v_blocks_custom_transcript_hero_trust_stats" USING btree ("_parent_id");
    CREATE INDEX IF NOT EXISTS "_pages_v_blocks_pricing_comparison_left_panel_features_order_idx" ON "_pages_v_blocks_pricing_comparison_left_panel_features" USING btree ("_order");
    CREATE INDEX IF NOT EXISTS "_pages_v_blocks_pricing_comparison_left_panel_features_parent_id_idx" ON "_pages_v_blocks_pricing_comparison_left_panel_features" USING btree ("_parent_id");
    CREATE INDEX IF NOT EXISTS "_pages_v_blocks_pricing_comparison_right_panel_features_order_idx" ON "_pages_v_blocks_pricing_comparison_right_panel_features" USING btree ("_order");
    CREATE INDEX IF NOT EXISTS "_pages_v_blocks_pricing_comparison_right_panel_features_parent_id_idx" ON "_pages_v_blocks_pricing_comparison_right_panel_features" USING btree ("_parent_id");
    CREATE INDEX IF NOT EXISTS "_pages_v_blocks_research_applications_applications_insights_order_idx" ON "_pages_v_blocks_research_applications_applications_insights" USING btree ("_order");
    CREATE INDEX IF NOT EXISTS "_pages_v_blocks_research_applications_applications_insights_parent_id_idx" ON "_pages_v_blocks_research_applications_applications_insights" USING btree ("_parent_id");
    CREATE INDEX IF NOT EXISTS "_pages_v_blocks_research_applications_applications_parent_id_idx" ON "_pages_v_blocks_research_applications_applications" USING btree ("_parent_id");
    CREATE INDEX IF NOT EXISTS "_pages_v_blocks_mockup_builder_transcript_content_sections_order_idx" ON "_pages_v_blocks_mockup_builder_transcript_content_sections" USING btree ("_order");
    CREATE INDEX IF NOT EXISTS "_pages_v_blocks_mockup_builder_transcript_content_sections_parent_id_idx" ON "_pages_v_blocks_mockup_builder_transcript_content_sections" USING btree ("_parent_id");
    CREATE INDEX IF NOT EXISTS "_pages_v_blocks_mockup_builder_dashboard_content_tiles_order_idx" ON "_pages_v_blocks_mockup_builder_dashboard_content_tiles" USING btree ("_order");
    CREATE INDEX IF NOT EXISTS "_pages_v_blocks_mockup_builder_dashboard_content_tiles_parent_id_idx" ON "_pages_v_blocks_mockup_builder_dashboard_content_tiles" USING btree ("_parent_id");
    CREATE INDEX IF NOT EXISTS "_pages_v_blocks_mockup_builder_chart_content_data_points_order_idx" ON "_pages_v_blocks_mockup_builder_chart_content_data_points" USING btree ("_order");
    CREATE INDEX IF NOT EXISTS "_pages_v_blocks_mockup_builder_chart_content_data_points_parent_id_idx" ON "_pages_v_blocks_mockup_builder_chart_content_data_points" USING btree ("_parent_id");

    DO $$ BEGIN ALTER TABLE "pages_blocks_pricing_comparison_left_panel_features" ADD CONSTRAINT "pages_blocks_pricing_comparison_left_panel_features_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_pricing_comparison"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
    DO $$ BEGIN ALTER TABLE "pages_blocks_pricing_comparison_right_panel_features" ADD CONSTRAINT "pages_blocks_pricing_comparison_right_panel_features_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_pricing_comparison"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
    DO $$ BEGIN ALTER TABLE "pages_blocks_research_applications_applications_insights" ADD CONSTRAINT "pages_blocks_research_applications_applications_insights_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_research_applications_applications"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
    DO $$ BEGIN ALTER TABLE "pages_blocks_testimonial_testimonials" ADD CONSTRAINT "pages_blocks_testimonial_testimonials_author_image_id_media_id_fk" FOREIGN KEY ("author_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
    DO $$ BEGIN ALTER TABLE "pages_blocks_mockup_builder_transcript_content_sections" ADD CONSTRAINT "pages_blocks_mockup_builder_transcript_content_sections_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_mockup_builder"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
    DO $$ BEGIN ALTER TABLE "pages_blocks_mockup_builder_dashboard_content_tiles" ADD CONSTRAINT "pages_blocks_mockup_builder_dashboard_content_tiles_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_mockup_builder"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
    DO $$ BEGIN ALTER TABLE "pages_blocks_mockup_builder_chart_content_data_points" ADD CONSTRAINT "pages_blocks_mockup_builder_chart_content_data_points_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_mockup_builder"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
    DO $$ BEGIN ALTER TABLE "_pages_v_blocks_free_transcript_hero_compliance_items" ADD CONSTRAINT "_pages_v_blocks_free_transcript_hero_compliance_items_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_free_transcript_hero"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
    DO $$ BEGIN ALTER TABLE "_pages_v_blocks_custom_transcript_hero_process_steps" ADD CONSTRAINT "_pages_v_blocks_custom_transcript_hero_process_steps_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_custom_transcript_hero"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
    DO $$ BEGIN ALTER TABLE "_pages_v_blocks_pricing_comparison_left_panel_features" ADD CONSTRAINT "_pages_v_blocks_pricing_comparison_left_panel_features_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_pricing_comparison"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
    DO $$ BEGIN ALTER TABLE "_pages_v_blocks_pricing_comparison_right_panel_features" ADD CONSTRAINT "_pages_v_blocks_pricing_comparison_right_panel_features_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_pricing_comparison"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
    DO $$ BEGIN ALTER TABLE "_pages_v_blocks_research_applications_applications_insights" ADD CONSTRAINT "_pages_v_blocks_research_applications_applications_insights_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_research_applications_applications"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
    DO $$ BEGIN ALTER TABLE "_pages_v_blocks_feature_spotlight" ADD CONSTRAINT "_pages_v_blocks_feature_spotlight_spotlight_image_id_media_id_fk" FOREIGN KEY ("spotlight_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
    DO $$ BEGIN ALTER TABLE "_pages_v_blocks_testimonial_testimonials" ADD CONSTRAINT "_pages_v_blocks_testimonial_testimonials_author_image_id_media_id_fk" FOREIGN KEY ("author_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
    DO $$ BEGIN ALTER TABLE "_pages_v_blocks_testimonial_testimonials" ADD CONSTRAINT "_pages_v_blocks_testimonial_testimonials_logo_image_id_media_id_fk" FOREIGN KEY ("logo_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
    DO $$ BEGIN ALTER TABLE "_pages_v_blocks_mockup_builder_transcript_content_sections" ADD CONSTRAINT "_pages_v_blocks_mockup_builder_transcript_content_sections_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_mockup_builder"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
    DO $$ BEGIN ALTER TABLE "_pages_v_blocks_mockup_builder_dashboard_content_tiles" ADD CONSTRAINT "_pages_v_blocks_mockup_builder_dashboard_content_tiles_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_mockup_builder"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
    DO $$ BEGIN ALTER TABLE "_pages_v_blocks_mockup_builder_chart_content_data_points" ADD CONSTRAINT "_pages_v_blocks_mockup_builder_chart_content_data_points_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_mockup_builder"("id") ON DELETE cascade ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
    DO $$ BEGIN ALTER TABLE "_pages_v_blocks_quote_spotlight" ADD CONSTRAINT "_pages_v_blocks_quote_spotlight_attribution_image_id_media_id_fk" FOREIGN KEY ("attribution_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
    DO $$ BEGIN ALTER TABLE "_expert_transcripts_v" ADD CONSTRAINT "_expert_transcripts_v_version_pdf_file_id_transcript_files_id_fk" FOREIGN KEY ("version_pdf_file_id") REFERENCES "public"."transcript_files"("id") ON DELETE set null ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN null; END $$;
  `)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  // D. Postgres truncates these names on lookup the same way it did on create.
  await db.execute(sql`
    ALTER TABLE "pages_blocks_pricing_comparison_left_panel_features" DROP CONSTRAINT IF EXISTS "pages_blocks_pricing_comparison_left_panel_features_parent_id_fk";
    ALTER TABLE "pages_blocks_pricing_comparison_right_panel_features" DROP CONSTRAINT IF EXISTS "pages_blocks_pricing_comparison_right_panel_features_parent_id_fk";
    ALTER TABLE "pages_blocks_research_applications_applications_insights" DROP CONSTRAINT IF EXISTS "pages_blocks_research_applications_applications_insights_parent_id_fk";
    ALTER TABLE "pages_blocks_testimonial_testimonials" DROP CONSTRAINT IF EXISTS "pages_blocks_testimonial_testimonials_author_image_id_media_id_fk";
    ALTER TABLE "pages_blocks_mockup_builder_transcript_content_sections" DROP CONSTRAINT IF EXISTS "pages_blocks_mockup_builder_transcript_content_sections_parent_id_fk";
    ALTER TABLE "pages_blocks_mockup_builder_dashboard_content_tiles" DROP CONSTRAINT IF EXISTS "pages_blocks_mockup_builder_dashboard_content_tiles_parent_id_fk";
    ALTER TABLE "pages_blocks_mockup_builder_chart_content_data_points" DROP CONSTRAINT IF EXISTS "pages_blocks_mockup_builder_chart_content_data_points_parent_id_fk";
    ALTER TABLE "_pages_v_blocks_free_transcript_hero_compliance_items" DROP CONSTRAINT IF EXISTS "_pages_v_blocks_free_transcript_hero_compliance_items_parent_id_fk";
    ALTER TABLE "_pages_v_blocks_custom_transcript_hero_process_steps" DROP CONSTRAINT IF EXISTS "_pages_v_blocks_custom_transcript_hero_process_steps_parent_id_fk";
    ALTER TABLE "_pages_v_blocks_pricing_comparison_left_panel_features" DROP CONSTRAINT IF EXISTS "_pages_v_blocks_pricing_comparison_left_panel_features_parent_id_fk";
    ALTER TABLE "_pages_v_blocks_pricing_comparison_right_panel_features" DROP CONSTRAINT IF EXISTS "_pages_v_blocks_pricing_comparison_right_panel_features_parent_id_fk";
    ALTER TABLE "_pages_v_blocks_research_applications_applications_insights" DROP CONSTRAINT IF EXISTS "_pages_v_blocks_research_applications_applications_insights_parent_id_fk";
    ALTER TABLE "_pages_v_blocks_feature_spotlight" DROP CONSTRAINT IF EXISTS "_pages_v_blocks_feature_spotlight_spotlight_image_id_media_id_fk";
    ALTER TABLE "_pages_v_blocks_testimonial_testimonials" DROP CONSTRAINT IF EXISTS "_pages_v_blocks_testimonial_testimonials_author_image_id_media_id_fk";
    ALTER TABLE "_pages_v_blocks_testimonial_testimonials" DROP CONSTRAINT IF EXISTS "_pages_v_blocks_testimonial_testimonials_logo_image_id_media_id_fk";
    ALTER TABLE "_pages_v_blocks_mockup_builder_transcript_content_sections" DROP CONSTRAINT IF EXISTS "_pages_v_blocks_mockup_builder_transcript_content_sections_parent_id_fk";
    ALTER TABLE "_pages_v_blocks_mockup_builder_dashboard_content_tiles" DROP CONSTRAINT IF EXISTS "_pages_v_blocks_mockup_builder_dashboard_content_tiles_parent_id_fk";
    ALTER TABLE "_pages_v_blocks_mockup_builder_chart_content_data_points" DROP CONSTRAINT IF EXISTS "_pages_v_blocks_mockup_builder_chart_content_data_points_parent_id_fk";
    ALTER TABLE "_pages_v_blocks_quote_spotlight" DROP CONSTRAINT IF EXISTS "_pages_v_blocks_quote_spotlight_attribution_image_id_media_id_fk";
    ALTER TABLE "_expert_transcripts_v" DROP CONSTRAINT IF EXISTS "_expert_transcripts_v_version_pdf_file_id_transcript_files_id_fk";

    DROP INDEX IF EXISTS "pages_blocks_free_transcript_hero_compliance_items_parent_id_idx";
    DROP INDEX IF EXISTS "pages_blocks_pricing_comparison_left_panel_features_parent_id_idx";
    DROP INDEX IF EXISTS "pages_blocks_pricing_comparison_right_panel_features_parent_id_idx";
    DROP INDEX IF EXISTS "pages_blocks_research_applications_applications_insights_order_idx";
    DROP INDEX IF EXISTS "pages_blocks_research_applications_applications_insights_parent_id_idx";
    DROP INDEX IF EXISTS "pages_blocks_mockup_builder_transcript_content_sections_order_idx";
    DROP INDEX IF EXISTS "pages_blocks_mockup_builder_transcript_content_sections_parent_id_idx";
    DROP INDEX IF EXISTS "pages_blocks_mockup_builder_dashboard_content_tiles_parent_id_idx";
    DROP INDEX IF EXISTS "pages_blocks_mockup_builder_chart_content_data_points_parent_id_idx";
    DROP INDEX IF EXISTS "_pages_v_blocks_free_transcript_hero_compliance_items_parent_id_idx";
    DROP INDEX IF EXISTS "_pages_v_blocks_custom_transcript_hero_process_steps_parent_id_idx";
    DROP INDEX IF EXISTS "_pages_v_blocks_custom_transcript_hero_trust_stats_parent_id_idx";
    DROP INDEX IF EXISTS "_pages_v_blocks_pricing_comparison_left_panel_features_order_idx";
    DROP INDEX IF EXISTS "_pages_v_blocks_pricing_comparison_left_panel_features_parent_id_idx";
    DROP INDEX IF EXISTS "_pages_v_blocks_pricing_comparison_right_panel_features_order_idx";
    DROP INDEX IF EXISTS "_pages_v_blocks_pricing_comparison_right_panel_features_parent_id_idx";
    DROP INDEX IF EXISTS "_pages_v_blocks_research_applications_applications_insights_order_idx";
    DROP INDEX IF EXISTS "_pages_v_blocks_research_applications_applications_insights_parent_id_idx";
    DROP INDEX IF EXISTS "_pages_v_blocks_research_applications_applications_parent_id_idx";
    DROP INDEX IF EXISTS "_pages_v_blocks_mockup_builder_transcript_content_sections_order_idx";
    DROP INDEX IF EXISTS "_pages_v_blocks_mockup_builder_transcript_content_sections_parent_id_idx";
    DROP INDEX IF EXISTS "_pages_v_blocks_mockup_builder_dashboard_content_tiles_order_idx";
    DROP INDEX IF EXISTS "_pages_v_blocks_mockup_builder_dashboard_content_tiles_parent_id_idx";
    DROP INDEX IF EXISTS "_pages_v_blocks_mockup_builder_chart_content_data_points_order_idx";
    DROP INDEX IF EXISTS "_pages_v_blocks_mockup_builder_chart_content_data_points_parent_id_idx";
  `)

  // C. Back to varchar (the JSON is kept as text)
  await db.execute(sql`
    ALTER TABLE "earnings_analyses"
      ALTER COLUMN "executive_summary_preview" TYPE varchar USING "executive_summary_preview"::text;
    ALTER TABLE "_earnings_analyses_v"
      ALTER COLUMN "version_executive_summary_preview" TYPE varchar USING "version_executive_summary_preview"::text;
  `)

  // B. Back to JSONB, wrapping each answer in a Lexical paragraph (as 20260526's down does)
  await db.execute(sql`
    ALTER TABLE "_pages_v_blocks_faq_items" ADD COLUMN IF NOT EXISTS "answer_jsonb" jsonb;
    UPDATE "_pages_v_blocks_faq_items"
    SET "answer_jsonb" = jsonb_build_object(
      'root', jsonb_build_object(
        'type', 'root',
        'children', jsonb_build_array(jsonb_build_object(
          'type', 'paragraph',
          'children', jsonb_build_array(jsonb_build_object('type', 'text', 'text', COALESCE("answer", '')))
        ))
      )
    )
    WHERE "answer" IS NOT NULL;
    ALTER TABLE "_pages_v_blocks_faq_items" DROP COLUMN "answer";
    ALTER TABLE "_pages_v_blocks_faq_items" RENAME COLUMN "answer_jsonb" TO "answer";
  `)

  // A.
  await db.execute(sql`
    DROP INDEX IF EXISTS "payload_locked_documents_rels_blog_leads_id_idx";
    ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_blog_leads_fk";
    ALTER TABLE "payload_locked_documents_rels" DROP COLUMN IF EXISTS "blog_leads_id";
  `)
}
